# Generated by Django 5.1.7 on 2025-03-25 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0005_alumno_materias_inscritas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='universidad.alumno')),
            ],
        ),
    ]
