# Generated by Django 5.1.7 on 2025-05-02 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0004_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='universidad.alumno')),
                ('materias', models.ManyToManyField(related_name='inscripciones', to='universidad.materia')),
            ],
        ),
    ]
