# Generated by Django 5.1.7 on 2025-05-09 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('universidad', '0005_inscripcion'),
    ]

    def insertData(self, schema_editor):
        Group = self.get_model('auth', 'Group')

        administrador = Group(name="Administrador")
        administrador.save()

        profesor = Group(name="Profesor")
        profesor.save()

        estudiante = Group(name="Estudiante")
        estudiante.save()

        registro = Group(name="Registro")
        registro.save()

    operations = [
        migrations.RunPython(insertData, atomic=True),
    ]
