# Generated by Django 5.1.7 on 2025-05-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0005_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
