# Generated by Django 5.1.7 on 2025-05-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0006_alumno_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
