# Generated by Django 5.1.7 on 2025-05-09 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('universidad', '0006_add_roles'),
    ]

    def insertData(self, schema_editor):
        Group = self.get_model('auth', 'Group')
        Permission = self.get_model('auth', 'Permission')

        profesor_group = Group.objects.get(name='Profesor')
        admin_group = Group.objects.get(name='Administrador')
        estudiante_group = Group.objects.get(name='Estudiante')
        registro_group = Group.objects.get(name='Registro')

        user_view = Permission.objects.get(codename='view_user')
        user_create = Permission.objects.get(codename='add_user')
        user_update = Permission.objects.get(codename='change_user')
        user_delete = Permission.objects.get(codename='delete_user')

        alumno_view = Permission.objects.get(codename='view_alumno')
        alumno_create = Permission.objects.get(codename='add_alumno')
        alumno_update = Permission.objects.get(codename='change_alumno')
        alumno_delete = Permission.objects.get(codename='delete_alumno')

        materia_view = Permission.objects.get(codename='view_materia')
        materia_create = Permission.objects.get(codename='add_materia')
        materia_update = Permission.objects.get(codename='change_materia')
        materia_delete = Permission.objects.get(codename='delete_materia')

        inscripcion_view = Permission.objects.get(codename='view_inscripcion')
        inscripcion_create = Permission.objects.get(codename='add_inscripcion')
        inscripcion_update = Permission.objects.get(codename='change_inscripcion')
        inscripcion_delete = Permission.objects.get(codename='delete_inscripcion')

        telefono_view = Permission.objects.get(codename='view_telefono')
        telefono_create = Permission.objects.get(codename='add_telefono')
        telefono_update = Permission.objects.get(codename='change_telefono')
        telefono_delete = Permission.objects.get(codename='delete_telefono')

        estudiante_group.permissions.set([
            alumno_view, materia_view, inscripcion_view, telefono_view, user_view
        ])

        profesor_group.permissions.set([
            alumno_view, materia_view, inscripcion_view, telefono_view, user_view
        ])
        registro_group.permissions.set([
            materia_view, materia_create, materia_update, materia_delete,
            inscripcion_view, inscripcion_create, inscripcion_update, inscripcion_delete,
            telefono_view, telefono_create, telefono_update, telefono_delete,
            alumno_view, alumno_create, alumno_update,
        ])

        admin_group.permissions.set([
            user_view, user_create, user_update, user_delete,
            alumno_view, alumno_create, alumno_update, alumno_delete,
            materia_view, materia_create, materia_update, materia_delete,
            inscripcion_view, inscripcion_create, inscripcion_update, inscripcion_delete,
            telefono_view, telefono_create, telefono_update, telefono_delete
        ])


    operations = [
        migrations.RunPython(insertData, atomic=True),
    ]
