# Generated by Django 5.1.7 on 2025-05-09 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('universidad', '0007_add_permissions'),
    ]

    def insertData(self, schema_editor):
        User = self.get_model('auth', 'User')
        Group = self.get_model('auth', 'Group')

        admin_user = User.objects.get(username='admin')
        if admin_user is None:
            admin_user = User.objects.create_user(
                username='admin',
                password='123456789',
                email='admin@admin.com'
            )
            admin_user.is_superuser = True
            admin_user.is_staff = True
            admin_user.save()

        admin_group = Group.objects.get(name='Administrador')

        admin_user.groups.add(admin_group)

    operations = [
        migrations.RunPython(insertData, atomic=True),
    ]
